import { ProjectsSectionType } from '@/lib/types/sections';
import { getId } from '@/lib/utils/helper';

export const projectsSection: ProjectsSectionType = {
  title: 'MY CERTIFICATES & DEPLOYED PROJECTS',
  projects: [
    {
      name: 'HTML CERTIFICATE',
      img: '/html.jpg',
      id: '',
      url: 'https://www.sololearn.com/en/certificates/CC-76PD1XIT',
      year: 0,
      tags: [],
      repo: ''
    },
    {
      id: getId(),
      name: 'CSS CERTIFICATE',
      url: 'https://www.sololearn.com/certificates/CC-11HWRSVP',
      repo: '',
      img: '/css.jpg',
      year: 0,
      tags: [],
    },
    {
      id: getId(),
      name: 'JAVASCRIPT CERTIFICATE',
      url: 'https://www.sololearn.com/en/certificates/CC-XQ8GTGD4',
      repo: '',
      img: '/javascript.jpg',
      year: 0,
      tags: [],
    },
    {
      id: getId(),
      name: 'C PROGRAMMING CERTIFICATE',
      url: 'https://www.sololearn.com/certificates/CC-0YYNJCOL',
      repo: '',
      img: '/c.jpg',
      year: 0,
      tags: [],
    },
    {
      id: getId(),
      name: 'JAVA CERTIFICATE',
      url: 'https://www.sololearn.com/en/certificates/CC-XIOVUXUE',
      repo: '',
      img: '/java.jpg',
      year: 0,
      tags: [],
    },
    {
      id: getId(),
      name: 'JAVA INTERMEDIATE CERTIFICATE',
      url: 'https://www.sololearn.com/en/certificates/CC-MIVRRDGJ',
      repo: '',
      img: '/java inter.jpg',
      year: 0,
      tags: [],
    },
    {
      id: getId(),
      name: 'CALCULATOR APP',
      url: 'https://calculator-by-kurt.vercel.app/',
      repo: 'https://github.com/kurtchinta/CALCULATOR',
      img: '/kurt.png',
      year: 0,
      tags: [],
    },
    {
      id: getId(),
      name: 'TO-DO LIST',
      url: 'https://reserva-act-3.vercel.app/',
      repo: '',
      img: '/image.png',
      year: 0,
      tags: [],
    },
    {
      id: getId(),
      name: 'WEATHER APP',
      url: 'https://weather-app-by-kurt.vercel.app/',
      repo: 'https://github.com/vatsalsinghkv/weather-app',
      img: '/weather-app.png',
      year: 0,
      tags: [],
    },
  ],
};
